/*
 * RestfulBooker Booking service
 * Booking service for Restful Booker. An application for teaching Automation in Testing
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark@mwtestconsultancy.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models.booking;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import models.booking.BookingDates;

/**
 * Booking
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-21T09:43:20.313482+01:00[Europe/Amsterdam]")
public class Booking {
  public static final String SERIALIZED_NAME_BOOKINGDATES = "bookingdates";
  @SerializedName(SERIALIZED_NAME_BOOKINGDATES)
  private BookingDates bookingdates;

  public static final String SERIALIZED_NAME_BOOKINGID = "bookingid";
  @SerializedName(SERIALIZED_NAME_BOOKINGID)
  private Integer bookingid;

  public static final String SERIALIZED_NAME_DEPOSITPAID = "depositpaid";
  @SerializedName(SERIALIZED_NAME_DEPOSITPAID)
  private Boolean depositpaid;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_FIRSTNAME = "firstname";
  @SerializedName(SERIALIZED_NAME_FIRSTNAME)
  private String firstname;

  public static final String SERIALIZED_NAME_LASTNAME = "lastname";
  @SerializedName(SERIALIZED_NAME_LASTNAME)
  private String lastname;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_ROOMID = "roomid";
  @SerializedName(SERIALIZED_NAME_ROOMID)
  private Integer roomid;


  public Booking bookingdates(BookingDates bookingdates) {
    
    this.bookingdates = bookingdates;
    return this;
  }

   /**
   * Get bookingdates
   * @return bookingdates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BookingDates getBookingdates() {
    return bookingdates;
  }



  public void setBookingdates(BookingDates bookingdates) {
    this.bookingdates = bookingdates;
  }


  public Booking bookingid(Integer bookingid) {
    
    this.bookingid = bookingid;
    return this;
  }

   /**
   * Get bookingid
   * @return bookingid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getBookingid() {
    return bookingid;
  }



  public void setBookingid(Integer bookingid) {
    this.bookingid = bookingid;
  }


  public Booking depositpaid(Boolean depositpaid) {
    
    this.depositpaid = depositpaid;
    return this;
  }

   /**
   * Get depositpaid
   * @return depositpaid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDepositpaid() {
    return depositpaid;
  }



  public void setDepositpaid(Boolean depositpaid) {
    this.depositpaid = depositpaid;
  }


  public Booking email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmail() {
    return email;
  }



  public void setEmail(String email) {
    this.email = email;
  }


  public Booking firstname(String firstname) {
    
    this.firstname = firstname;
    return this;
  }

   /**
   * Get firstname
   * @return firstname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFirstname() {
    return firstname;
  }



  public void setFirstname(String firstname) {
    this.firstname = firstname;
  }


  public Booking lastname(String lastname) {
    
    this.lastname = lastname;
    return this;
  }

   /**
   * Get lastname
   * @return lastname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLastname() {
    return lastname;
  }



  public void setLastname(String lastname) {
    this.lastname = lastname;
  }


  public Booking phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPhone() {
    return phone;
  }



  public void setPhone(String phone) {
    this.phone = phone;
  }


  public Booking roomid(Integer roomid) {
    
    this.roomid = roomid;
    return this;
  }

   /**
   * Get roomid
   * @return roomid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getRoomid() {
    return roomid;
  }



  public void setRoomid(Integer roomid) {
    this.roomid = roomid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Booking booking = (Booking) o;
    return Objects.equals(this.bookingdates, booking.bookingdates) &&
        Objects.equals(this.bookingid, booking.bookingid) &&
        Objects.equals(this.depositpaid, booking.depositpaid) &&
        Objects.equals(this.email, booking.email) &&
        Objects.equals(this.firstname, booking.firstname) &&
        Objects.equals(this.lastname, booking.lastname) &&
        Objects.equals(this.phone, booking.phone) &&
        Objects.equals(this.roomid, booking.roomid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bookingdates, bookingid, depositpaid, email, firstname, lastname, phone, roomid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Booking {\n");
    sb.append("    bookingdates: ").append(toIndentedString(bookingdates)).append("\n");
    sb.append("    bookingid: ").append(toIndentedString(bookingid)).append("\n");
    sb.append("    depositpaid: ").append(toIndentedString(depositpaid)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    roomid: ").append(toIndentedString(roomid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

