/*
 * RestfulBooker Booking service
 * Booking service for Restful Booker. An application for teaching Automation in Testing
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark@mwtestconsultancy.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models.booking;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.IOException;

/**
 * BookingDates
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-21T09:43:20.313482+01:00[Europe/Amsterdam]")
public class BookingDates {
  public static final String SERIALIZED_NAME_CHECKIN = "checkin";
  @JsonFormat(pattern="yyyy-MM-dd")
  @DateTimeFormat(iso = DateTimeFormat.ISO.TIME)
  @SerializedName(SERIALIZED_NAME_CHECKIN)
  private LocalDate checkin;

  public static final String SERIALIZED_NAME_CHECKOUT = "checkout";
  @JsonFormat(pattern="yyyy-MM-dd")
  @DateTimeFormat(iso = DateTimeFormat.ISO.TIME)
  @SerializedName(SERIALIZED_NAME_CHECKOUT)
  private LocalDate checkout;


  public BookingDates checkin(LocalDate checkin) {
    
    this.checkin = checkin;
    return this;
  }

   /**
   * Get checkin
   * @return checkin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getCheckin() {
    return checkin;
  }



  public void setCheckin(LocalDate checkin) {
    this.checkin = checkin;
  }


  public BookingDates checkout(LocalDate checkout) {
    
    this.checkout = checkout;
    return this;
  }

   /**
   * Get checkout
   * @return checkout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getCheckout() {
    return checkout;
  }



  public void setCheckout(LocalDate checkout) {
    this.checkout = checkout;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookingDates bookingDates = (BookingDates) o;
    return Objects.equals(this.checkin, bookingDates.checkin) &&
        Objects.equals(this.checkout, bookingDates.checkout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkin, checkout);
  }

}

