/*
 * RestfulBooker Booking service
 * Booking service for Restful Booker. An application for teaching Automation in Testing
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark@mwtestconsultancy.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models.booking;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import models.booking.Booking;

/**
 * CreatedBooking
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-21T09:43:20.313482+01:00[Europe/Amsterdam]")
public class CreatedBooking {
  public static final String SERIALIZED_NAME_BOOKING = "booking";
  @SerializedName(SERIALIZED_NAME_BOOKING)
  private Booking booking;

  public static final String SERIALIZED_NAME_BOOKINGID = "bookingid";
  @SerializedName(SERIALIZED_NAME_BOOKINGID)
  private Integer bookingid;


  public CreatedBooking booking(Booking booking) {
    
    this.booking = booking;
    return this;
  }

   /**
   * Get booking
   * @return booking
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Booking getBooking() {
    return booking;
  }



  public void setBooking(Booking booking) {
    this.booking = booking;
  }


  public CreatedBooking bookingid(Integer bookingid) {
    
    this.bookingid = bookingid;
    return this;
  }

   /**
   * Get bookingid
   * @return bookingid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getBookingid() {
    return bookingid;
  }



  public void setBookingid(Integer bookingid) {
    this.bookingid = bookingid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatedBooking createdBooking = (CreatedBooking) o;
    return Objects.equals(this.booking, createdBooking.booking) &&
        Objects.equals(this.bookingid, createdBooking.bookingid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(booking, bookingid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatedBooking {\n");
    sb.append("    booking: ").append(toIndentedString(booking)).append("\n");
    sb.append("    bookingid: ").append(toIndentedString(bookingid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

