/*
 * RestfulBooker Booking service
 * Booking service for Restful Booker. An application for teaching Automation in Testing
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark@mwtestconsultancy.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package models.booking;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Optionalstring
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-21T09:43:20.313482+01:00[Europe/Amsterdam]")
public class Optionalstring {
  public static final String SERIALIZED_NAME_EMPTY = "empty";
  @SerializedName(SERIALIZED_NAME_EMPTY)
  private Boolean empty;

  public static final String SERIALIZED_NAME_PRESENT = "present";
  @SerializedName(SERIALIZED_NAME_PRESENT)
  private Boolean present;


  public Optionalstring empty(Boolean empty) {
    
    this.empty = empty;
    return this;
  }

   /**
   * Get empty
   * @return empty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getEmpty() {
    return empty;
  }



  public void setEmpty(Boolean empty) {
    this.empty = empty;
  }


  public Optionalstring present(Boolean present) {
    
    this.present = present;
    return this;
  }

   /**
   * Get present
   * @return present
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getPresent() {
    return present;
  }



  public void setPresent(Boolean present) {
    this.present = present;
  }


  @Override
  public int hashCode() {
    return Objects.hash(empty, present);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Optionalstring {\n");
    sb.append("    empty: ").append(toIndentedString(empty)).append("\n");
    sb.append("    present: ").append(toIndentedString(present)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

